//
//  SFImage.swift
//  InTechs (iOS)
//
//  Created by GoEun Jeong on 2021/08/22.
//

import Foundation

enum SFImage: String {
    case command = "command.square"
    case questionSquare = "questionmark.square"
    case mention = "at"
    case edit = "square.and.pencil"
    case dot = "ellipsis"
    case search = "magnifyingglass"
    case info = "info.circle"
    case star = "star"
    case bell = "bell"
    case filledDownArrow = "arrowtriangle.down.fill"
    case clip = "paperclip"
    case smileFace = "face.smiling.fill"
    case photo = "photo"
    case person = "person.crop.circle"
    case people = "person.2.fill"
    case issue = "flame"
    case checklist = "checkmark.square.fill"
    case plus = "plus"
    case downArrow = "chevron.down"
    case upArrow = "chevron.up"
    case square = "square"
    case xmark = "xmark"
    case chat = "message.fill"
    case project = "square.grid.2x2"
    case calendar = "calendar"
    case question = "questionmark"
    case plusSquare = "plus.app.fill"
    case emailFill = "envelope.fill"
    case lockFill = "lock.fill"
    case leftArrow = "chevron.left"
    case rightArrow = "chevron.right"
    case minus = "minus"
    case upAndDownArrow = "arrow.up.arrow.down"
    case DM = "envelope"
    case house = "house.fill"
    case paperplane = "paperplane"
    case paperplaneFill = "paperplane.fill"
    case camera = "camera"
    case lockShield = "lock.shield"
    case checkmarkShield = "checkmark.shield"
    case copy = "square.on.square"
    case checkmark = "checkmark"
    case circle = "circle"
    case circleFill = "largecircle.fill.circle"
    case checkmarkSquare = "checkmark.square"
    case pencil = "pencil"
    case trash = "trash"
    case pin = "pin"
    case bellSlash = "bell.slash"
    case xmarkCircle = "xmark.circle.fill"
    case threadPlus = "plus.message"
    case checkmarkCircleFill = "checkmark.circle.fill"
    case logout = "clear.fill"
    case setting = "gearshape"
    case download = "square.and.arrow.down"
    case speaker = "speaker.wave.2"
}
